name: Generate Tetris Contribution Animation

on:
  schedule:
    - cron: "0 1 * * *"     # once a day
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: kubowania/github-contribution-tetris@v1
        with:
          github_user_name: KoriSamaksh

      - name: Push to tetris branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: tetris
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
